### ISSUE TITLE
Support Safari and IE

### ISSUE THREAD

**Issue by jenschelkopf** [zalmoxisus/redux-remotedev#3]
This library doesn't work for users on Safari and IE because those browsers haven't implemented the Fetch spec yet - see [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). 

I've had good luck with [axios](https://github.com/mzabriskie/axios), but there's also a popular Fetch [polyfill](https://github.com/github/fetch). 

If it's expected for this library to not to work in Safari and IE it would be nice to document that in the README.

**Comment by zalmoxisus** [comment]
Yes, it's already [indicated in the README](https://github.com/zalmoxisus/redux-remotedev#sender), but it makes sense to specify also in [the usage](https://github.com/zalmoxisus/redux-remotedev#usage). We don't include it out of the box, because we support also React Native, and anyway it's better to keep it outside the lib.

Libraries like `axios` are great, but too large for our simple use case. However, if the consumer code already includes a specific lib, it's better to reuse it in [`sender` function](%28https://github.com/zalmoxisus/redux-remotedev#sender%29).

**Comment by zalmoxisus** [comment]
Added details. Thanks for the heads up!

**Comment by jenschelkopf** [comment]
Ah, I missed that. The clarification in the readme is great. Thanks!
